#! /usr/bin/env python3

import os, sys, re

decl = sys.argv[1]
filename = sys.argv[2]

file = open(filename, 'r')

print(f'{decl} = ')
text = file.read(-1)
lines = text.splitlines()
for line in lines:
    line.replace(r'\\', r'\\\\')
    line.replace(r'"', r'\\"')
    print(f'"{line}"')
print(';')
