#! /usr/bin/env python3

import os
import sys
import re

try:
    decl = sys.argv[1]
except IndexError:
    sys.stderr.write("stringize: missing declaration: {}\n".format(sys.argv))
    sys.exit(1)

try:
    filename = sys.argv[2]
except IndexError:
    sys.stderr.write("stringize: missing filename: {}\n".format(sys.argv))
    sys.exit(1)

file = open(filename, 'r')

print(f'{decl} = ')
text = file.read(-1)
lines = text.splitlines()
for line in lines:
    line.replace(r'\\', r'\\\\')
    line.replace(r'"', r'\\"')
    print(f'"{line}"')
print(';')
