name: Linux CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install build dependencies
        run: sudo apt update && sudo apt install -y gcc g++ libfreetype6-dev libharfbuzz-dev meson freeglut3-dev libglew-dev
      - name: Meson setup
        run: meson setup build
      - name: Meson compile
        run: meson compile -C build
